### ISSUE TITLE
Incorrect Java 19 version checking in 4.5.1 ZIPs

### ISSUE THREAD

**Issue by khumba** [squirrel-sql-client/squirrel-sql-code#13]
Hi!

Squirrel SQL 4.5.1 adds support for Java 18 and 19, via commits 7978596a and f869b3a1.  Various launcher scripts got updated, but it seems that the `squirrel-sql.sh` in the root of `squirrelsql-4.5.1-standard.zip` wasn't updated and is still limited to Java 17.  I am not sure if this is the reason, but I see that none of the scripts in `sql12/plainZipScripts` were updated by these commits, and all of these are limited to Java 17 as well.  This is causing problems downstream in Nixpkgs[1].

Do we just need to update these remaining scripts, or is there more to it than that?  I don't know anything about Squirrel's release process.

Thanks in advance.

[1] https://github.com/NixOS/nixpkgs/pull/235096

**Comment by gerdwagner** [comment]
Is fixed. I just released 4.6.0 which works with Java versions 11 to 20. You may download the plain zip versions here
https://github.com/squirrel-sql-client/squirrel-sql-stable-releases/releases/tag/4.6.0-a_plainzip
or here 
https://sourceforge.net/projects/squirrel-sql/files/1-stable/4.6.0-plainzip/

**Comment by khumba** [comment]
Thank you very much for the fix!
