### ISSUE TITLE
4.6.0 – DB Login dialog without user field

### ISSUE THREAD

**Issue by pstueck** [squirrel-sql-client/squirrel-sql-code#14]
The latest stable and snapshot version do no longer have a `User` field in the database login dialog.

Tried with and without look&feel plugin – no change … both variants do not have a `User` field.
Also tried to deactivate almost all plugins – the very same … still no `User` field.

Please bring back that field in the login dialog.
_When handling multiple logins for the very same database, auto-type of a password safe is much more convenient than having multiple connections to the same database._

Thanks, Peter

**Comment by gerdwagner** [comment]
Is fixed. Sorry for the inconvenience.
Excerpt from change log:
`The DB login dialog was missing the user name text field.
 The DB login dialog is shown when an Alias without auto logon is connected.`

A snapshot with the fix can be downloaded here
https://github.com/squirrel-sql-client/squirrel-sql-snapshot-releases/releases/tag/snapshot-20230613_2108
or here
https://sourceforge.net/projects/squirrel-sql/files/3-snapshots/snapshot-20230613_2108/

It would be nice if you could give it a try.

**Comment by pstueck** [comment]
No sweat!

Looks fixed – and also gets the focus when opened (not the display area as before). :+1:
_Finally I can ditch all that special SQuirreL login auto-types :grin: (which needed to start with a TAB)_

**Comment by gerdwagner** [comment]
Glad to hear. Thanks for checking it out.
