### ISSUE TITLE
Change request: show “Rows <Limit Rows:>” instead of “Limited to <Limit Rows:> rows” for <Limit Rows:> results

### ISSUE THREAD

**Issue by pstueck** [squirrel-sql-client/squirrel-sql-code#15]
The “Limited to <Limit Rows:> rows” information is shown, as soon as `<Limit Rows:>` are read.

Suggestion: show “Limited to <Limit Rows:> rows” only, if the query returns at least `<Limit Rows:> + 1` rows.

e.g. limit rows is set to 50
_actually: the “limited to” information is shown, no matter if the query returns 50, 51 or more rows in the result set._
**suggestion:** the “limited to” information is only shown, if the query would return at least 51 rows.

Thanks, Peter

**Comment by gerdwagner** [comment]
Is fixed and will be available in future snapshots and versions. Excerpt from our change log:
SQL result: The display of the result row limit was corrected
in case the number of rows read matched the number of rows in the result.
