### ISSUE TITLE
Wrong release date of 4.6.0 in the change log.

### ISSUE THREAD

**Issue by fml2** [squirrel-sql-client/squirrel-sql-code#16]
In the change log, the release date of `4.6.0` is written as [06/04/2022](https://github.com/squirrel-sql-client/squirrel-sql-code/blob/d7348a8157ff59dafa2f8bdb94a92318b734d371/sql12/core/doc/changes.txt#L37C8-L37C18). However, the correct year would be 2023.

**Comment by gerdwagner** [comment]
Thanks for the pointer.
Is fixed in our GIT repository and the latest news section of our home page.
