### ISSUE TITLE
Bytea decode and show as image.

### ISSUE THREAD

**Issue by sstefanov** [squirrel-sql-client/squirrel-sql-code#34]
I didn't found how to show saved PNG image in bytea field in postgresql database.
Please, add this feature, just like DBeaver do it.
If possible, add decoder options how to display field content. The data can be image, sound, etc.

**Comment by gerdwagner** [comment]
A new snapshot with the option to view cell contents as image is being releases. (Further options as sound or movie may be added later).
Excerpt from change log:

> SQL result table:
>   - Option to display cell details on the left of the table, see new toggle button with flip chart icon.
>   - Option to view contents of cell detail or cell data popup as image.

**Comment by sstefanov** [comment]
It works perfect!
Thank you very much for all work!

**Comment by sstefanov** [comment]
It works perfect!
Thank you very much for all work!

**Comment by gerdwagner** [comment]
Thanks for your feedback.
