### ISSUE TITLE
Feature request: Auto format XML/JSON values in the "display cell value" dialog

### ISSUE THREAD

**Issue by fml2** [squirrel-sql-client/squirrel-sql-code#41]
I have to view XML values quite often. There is a button to pretty format an XML value (or a JSON one).

Would it be possible to apply the formatting automatically? I.e. I click on the cell that contains XML data (a window pops up); this fact is somehow detected, and if the contents is recognized as XML, the string is automatically formatted (this should of course be optional, i.e. a new option is needed).

The same applies to JSON.

Another wish in this regard: it would be nice to be able to switch to the original value after it's been formatted (without closing the window). Also, an indicator would be cool showing that a formatted value (and not the original one) is displayed.

Thank you!

**Comment by gerdwagner** [comment]
If you double click a table cell the dialog that opens offers a button to format XMLs and Jsons.
Not a long ago this feature was made available for more data types than before. So if you find the feature is missing somewhere you may want to try out the latest snapshot available here
https://sourceforge.net/projects/squirrel-sql/files/3-snapshots/snapshot-20240915_2219/

or here
https://github.com/squirrel-sql-client/squirrel-sql-snapshot-releases/releases/tag/snapshot-20240915_2219

**Comment by fml2** [comment]
Yes, I meant exact this dialog. My proposal is that after I double click a cell, its contents is somehow analyzed and is then displayed already formatted -- without me having to click on a button. This auto formatting should only happen if a (new) option is activated.

The other wish was to be able to switch back to the original value(no matter how it was formatted -- automatically or not) and have an indicator whether the original or the formatted value is displayed.

**Comment by fml2** [comment]
Wow! Thank you!!!

**Comment by t603** [comment]
> The following behavior was implemented and will be available in future snapshots and versions (excerpt from change log):
> 
> #617 | #41 SQL result table: The detail data display now allows to automatically reformat XML or Json data. To configure automatic reformatting go to menu File --> Global preferences --> tab "Data type controls" --> section General Note: For detail data display double click a table cell or switch on cell detail display. Furthermore the reformat button was made a toggle button which allows to switch back to the unformatted data.

I have raised almost the same RFE as fml (and no, we are not from the same company ;-) and we do not know each other), see "[https://sourceforge.net/p/squirrel-sql/feature-requests/617/](https://sourceforge.net/p/squirrel-sql/feature-requests/617/)" and the build "squirrel-sql-snapshot-20241023_2105-standard.jar" contains the change implementing requested feature and it works great. We tested it for two days in our team and it looks like with not errors. Regards, Stepan

**Comment by fml2** [comment]
Ah, now I understand what "#617" means! :-)

**Comment by fml2** [comment]
I have (at last!) tested the change. Works like a charm! Thank you! What a pleasure this new feature is!

One more little question: Is it possible to configure the detail (cell value) view dialog so that it is reused when another cell is double clicked? As of now, each doble click produces a new dialog instance. If I want to quickly inspect several cells with XML, I end up with many open dialogs. A solution would be that, if a "Value details" dialog is already open, it gets reused for displaying a cell value on double click (without opening a new dialog instance).

**Comment by fml2** [comment]
I've created #45 for the last request; closing this issue.
