### ISSUE TITLE
Maximum string length of 10 000 to show in default cell detail display reached for column null:DATA_CLOB (CLOB)

### ISSUE THREAD

**Issue by t603** [squirrel-sql-client/squirrel-sql-code#43]
Hello, 

I have switched to SQuirreL SQL Client 4.8.0 now. I have a problem with displaying content of CLOB (Oracle 23 JDBC driver connection) cell both in pop-up window or right size non-pop-up window. The message 

**Maximum string length of 10 000 to show in default cell detail display reached for column null:DATA_CLOB (CLOB)** 

appears in SQuirreL log window and in data pop-up or right side cell window the content is substring of first 10000 characters. I searched for a long time in Preferences, where to increase this 10000 character limit, but no luck. Previous versions of SQuirreL SQL Client do not have such a limit. 

The content of the cell is loaded completely in normal table view with no string length restriction (verified by Copy&Paste to some editor). Both Global Preferences -> Data Type Controls -> BLOB and CLOB I set Read contents when table is first loaded Read all. When I do not use Oracle, but ELK, there data type is TEXT, the content of cell appears without restriction of length (22000 characters are displayed). 

May I ask for help, how to solve this issue? Regards, Stepan

**Comment by t603** [comment]
Hello, 

I have downloaded the source code of master branch of SQuirreL and it looks like the value 10000 is hardcoded in the file ".\squirrel-sql-code-master\sql12\core\src\net\sourceforge\squirrel_sql\fw\datasetviewer\cellcomponent\BigDataRenderResult.java" 

`public static final int MAX_BYTES_IN_CELL_DETAIL_DISPLAY = 10000; `

So I guess, it would be nice to enable user to set up his own value (default 10000) in Global Preferences. 

Because I tried a little fake in Oracle database: 

`select "MY_CLOB", to_nclob("MY_CLOB") as "FAKE" from "MY_TABLE";  `

The first column appears in pop-up window or right side window restricted to the first 10000 characters, while the second column appears unrestricted (because restriction is done for BLOB or CLOB, not NCLOB). Both columns have the same performance (I guess, that the limit 10000 is set up due performance issues). Right mouse click and Reformat as XML/JSON works fine, even it is hidden on mouse context menu and not in bottom of the window icon. 

Regards, Stepan 

P. S. Once working on this feature, please notice my RFE on SourceForge regarding similar functionality "#617 Add XML/JSON to Select display: (Default|Image) and shown content of any type already formatted" on [https://sourceforge.net/p/squirrel-sql/feature-requests/617/](url)

**Comment by gerdwagner** [comment]
The following was implemented and will be available in future snapshots and versions, excerpt from change log:

> The maximum number of characters to display in the table cell data popup can now be configured.
> See menu File -- > Global Preferences --> tab General --> section "Table cell data value popup".

**Comment by t603** [comment]
> The following was implemented and will be available in future snapshots and versions, excerpt from change log:
> 
> > The maximum number of characters to display in the table cell data popup can now be configured.
> > See menu File -- > Global Preferences --> tab General --> section "Table cell data value popup".

Gerd, it works great! 

We are happy with this new feature. And it works fast on strings of length 100.000 characters. We have "-Xmx8192m" in "squirrel-sql.bat", so it may be the reason, why such long strings work very fast. I have tested it on "squirrel-sql-snapshot-20241028_1950-standard.jar". 

Thank You very much. One can close it as Implemented. Regards, Stepan
