### ISSUE TITLE
Numeric data right aligned (even to decimal separator) in ResultSet table

### ISSUE THREAD

**Issue by t603** [squirrel-sql-client/squirrel-sql-code#44]
Hello SQuirreL SQL team, 

I would like to ask You for an improvement regarding numeric data right alignment (even to decimal separator) in ResultSet table. Today when I select numeric (tinyint, smallint, int, bigint, decimal, real, generic numeric...) data, they are aligned to the left same as string, lob, timestamp... And it is hard to read numeric data in column. 

I would like to have numeric data aligned to the right (setting e. g. in Global Preferences -> Data Type Controls -> FLOAT...). This setting could be done in simple way (align to the right) or in more sophisticated way (align to the right by decimal separator like comma, dot) only in case of noninteger datatypes. The sophisticated way could be influenced by already implemented minimum and maximum number of decimal digits in Data Type Controls. The behavior would result in the same behavior like in current spreadsheet applications. 

For better explanation one can see attached screenshot comparing current look in SQuirreL SQL and MS Excel. 

Thank You in advantage, Stepan 

![SQuirreLSQL_RfeNumericDataRightAlignedToDecimalSeparator](https://github.com/user-attachments/assets/3a235813-8a3d-48e7-a619-94d5802ef0cd)

**Comment by gerdwagner** [comment]
The following was implemented and will be available in future snapshots and versions (excerpt from change log):

>   SQL result table: Numeric values can now be right aligned,
>   see menu File --> Global Preferences tab Data Types --> section "General"

**Comment by t603** [comment]
Hello, Gerd, I tried it on "squirrel-sql-snapshot-20241103_2144-standard.jar" just now and it works as I kindly asked. Great, Thank You very much. Kind regards, Stepan
