### ISSUE TITLE
Basic formatting of only the first line (header) of XLSX export: Bold, Center, Filter, Freeze Top Row

### ISSUE THREAD

**Issue by t603** [squirrel-sql-client/squirrel-sql-code#46]
Hello, SQuirreL team, 

may I ask You for improvement of XLSX export? I would like to propose basic formatting of only the first line (header) of XLSX export. If it is possible. 

I propose to apply these four "actions" to only the first line (header) of XLSX export: Bold, Center, Filter, Freeze Top Row. I always do it manually for users, which is time consuming, and they appreciate it very much comparing no formatting XLSX output. 

One can see desired output in attached screenshot. 

Thank You in advance, Stepan 

![SQuirreLSQL_RfeBasicFormattingHeaderOfXlsxOutput](https://github.com/user-attachments/assets/c81655b4-452e-47ee-b0a6-edc9e77ccde3)

**Comment by gerdwagner** [comment]
Committed to our GIT repositories. Will be available in future snapshots and versions.

Excerpt from change log:

> https://github.com/squirrel-sql-client/squirrel-sql-code/issues/46
>   SQL result and table export to MS-Excel files: New options to make exported sheets
>   auto filtered and to choose if header rows are bold, centered and/or frozen.
>   Note: Export to MS-Excel files and other formats is available through the right mouse menu of tables.
>   The SQL editor allows to export SQL results through the right mouse menu and tools popup (ctrl+t).

**Comment by gerdwagner** [comment]
Fixed in our Git repository, will be available in future snapshots and versions. Excerpt from change log:

```
Follow up to https://github.com/squirrel-sql-client/squirrel-sql-code/issues/46
SQL result and table export to MS-Excel files: The options to make header rows bold and centered did not 
  work for MS-Excel but for Libre Office only.
  Details of the fix:
  - Apache-Poi was upgraded to version 5.3.0.
  - SQuirreL deliberately dropped dependency on Log4J in 2022. As Apache-Poi 5.3.0 directly depends 
    on Log4J, SQuirreL now has a Log4J mock to make Apache-Poi 5.3.0 work. 
```

**Comment by fml2** [comment]
I've tried the Excel export with SQuirreL SQL Client snapshot-20241124_1922. One glithch that I noticed is that there is an extra column in Excel. I.e. if I export a table having **four** columns (with "Auto filter" selected), in the Excel I see the filter sign (a drop down button in the first row) in **five** columns.

**Comment by t603** [comment]
I have tested it too on "squirrel-sql-snapshot-20241124_1922-standard.jar" on Adoptium OpenJDK 17 on Windows 11. Auto filter OK, First row frozen OK, First row centered OK, First row bold OK. 

There are two little problems: 

- One more column in header, as described by @fml2. See the first screenshot below, red square. It looks like +1 problem of counting of columns in ResultSet (first is 0 or 1)? 
- When Opening in LibreOffice 24.8 (on Windows), there is message about corrupted file. But when I click Yest (repair file), it opens OK. See the second screenshot below. But who knows, it could be lack of some feature or reading XLSX in LibreOffice. So I just notice it to anybody knows about it. I do not complain about this. Well, and in LibreOffice is one more column too. 

Regards, Stepan 

Screenshot 01: MS Excel, one more column problem. 
![Screenshot 2024-11-25 132934](https://github.com/user-attachments/assets/39d4df01-8a26-4fe0-bc3a-82b3eeaf5aab)

Screenshot 02: LibreOffice, message about corrupted file. 
![Screenshot 2024-11-25 133122](https://github.com/user-attachments/assets/98df3471-5d03-4383-9b70-686af8f6fa8b)

```
--H2 2.3.232 InMemory 
drop table if exists "t"; 
create table "t" ("id" int, "name" varchar(256)); 
insert into "t" ("id", "name") values (1, 'aaa'), (2, 'bbb'), (3, 'ccc'); 
@msExcelWorkbook 'E:\Temp\formatting_01.xlsx' @sheet 'List1' select * from "t"; 
```

**Comment by t603** [comment]
"One more column" problem is just only filtered, not centered, not bolded. So just only AutoFilter is applied do the C, the third, column.

**Comment by gerdwagner** [comment]
The One more column filtered problem was already fixed last Monday (11/25/2024). Excerpt from change log:

> 
> https://github.com/squirrel-sql-client/squirrel-sql-code/issues/46
>   Excel export: The "Auto filter" option activated the auto filter for
>   one extra (empty) column at the end of the Excel sheet.
