### ISSUE TITLE
Mac detected wrong jdk

### ISSUE THREAD

**Issue by quantrpeter** [squirrel-sql-client/squirrel-sql-code#5]
<img width="715" alt="Screenshot 2022-10-01 at 4 52 06 PM" src="https://user-images.githubusercontent.com/50471577/193401467-47f1b55b-1503-4af6-a3c5-a0d8e1c33f10.png">

```
/Users/peter/workspace/qemu-log-panel>/usr/libexec/java_home -V
Matching Java Virtual Machines (4):
    18.0.1.1 (x86_64) "Oracle Corporation" - "Java SE 18.0.1.1" /Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home
    17.0.1 (x86_64) "Oracle Corporation" - "Java SE 17.0.1" /Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
    1.8.341.10 (x86_64) "Oracle Corporation" - "Java" /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home
    1.8.0_341 (x86_64) "Oracle Corporation" - "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_341.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk-18.0.1.1.jdk/Contents/Home
```

**Comment by gerdwagner** [comment]
SQuirreL's start scripts are not able to detect the right Java Virtual Machine they pick the one from the JAVA_HOME variable and if JAVA_HOME is not specified they pick the first from the PATH variable.

A simple fix is to add an `export JAVA_HOME=<path to Java directory>` in the line after "#! /bin/sh -x" of the squirrel-sql.sh script.

**Comment by quantrpeter** [comment]
sorry still have problem, i have set the JAVA_HOME in squirrel-sql.sh

<img width="693" alt="image" src="https://user-images.githubusercontent.com/50471577/193460262-8c982e82-78ba-4933-8e92-45b24cacedef.png">

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/50471577/193460281-1dfe6eaf-77cf-4532-9a04-0e7c9a3fde2a.png">

**Comment by quantrpeter** [comment]
For your reference, after i add this line it works

<img width="1298" alt="Screenshot 2022-10-02 at 10 53 49 PM" src="https://user-images.githubusercontent.com/50471577/193460596-e4dc0d55-7d14-4776-84cf-ed830da2b5f5.png">

**Comment by gerdwagner** [comment]
Thanks for the information. Perhaps it can/needs to be turned into another alternative for the SQUIRREL_SQL_HOME alternative. It would be nice if you had a look at the following:
![grafik](https://user-images.githubusercontent.com/5216139/194395287-38a388d7-31e7-441f-a5c1-7a8ab613c3b9.png)
