### ISSUE TITLE
BUG: Export of numeric values to CSV contains grouping separator

### ISSUE THREAD

**Issue by t603** [squirrel-sql-client/squirrel-sql-code#50]
Hello, SQuirreL SQL team, 

I have a problem with export of numeric values to CSV, both visual and macro (file ... .csv). When ResultSet contains numeric values, it is exported (saved) with grouping separator inside numeric values. So for example when grouping separator is single space, the CSV contains space too and not only common space, but even non-breaking space. 

Once someone wants to import (read) such CSV into Excel, H2 (any other database), such import fails or numeric values are treated as string, which is unwanted, and one has to perform several replaces even Regular Expression ones. I believe, that exporting grouping separators have only negatives and no positives. **So I would like to change behaviour of SQuirreL: Even there is defined any grouping separator (which is great and must for visual human readability) in SquirreL, when exporting into CSV, there is no grouping separator at all in CSV file.** I believe, this is not task for some extra preferences (export grouping separator), grouping separator should not be exported never. 

Thank You for understanding, Stepan 

Here is couple of screenshots, which illustrate above problem. Below I compare result of CSV export of SQuirreL with H2 native [csvwrite](https://www.h2database.com/html/functions.html#csvwrite) function. 

Screenshot 01: drop, create, insert into, select table, then export using macro and export directly from H2 using its csvwrite function: 
![Screenshot 2024-11-20 113128](https://github.com/user-attachments/assets/11b38364-088b-4376-9099-1e2d2a5509e2)

Screenshot 02: Comparing results of CSV export of SQuirreL vs H2 seen in text editor (oXygen). See grouping separator in SQuirreL export, which is non-breaking space.  
![Screenshot 2024-11-20 113321](https://github.com/user-attachments/assets/1764470a-d8e4-4a23-8c79-e52a42ce3ebe)

Screenshot 03: XLSX export also does not contain grouping separator. See XML source of XLSX produced by SQuirreL XLSX export. 
![Screenshot 2024-11-20 114158](https://github.com/user-attachments/assets/8b6354bb-f167-433d-b091-2ff133242c8b)

Screenshot 04: Opening of CSV produced by SQuirreL results in unsolvable problem (in Excel).  
![Screenshot 2024-11-20 115306](https://github.com/user-attachments/assets/631b7a5b-5a37-4fe0-9d45-1b6e128648f3)

**Comment by gerdwagner** [comment]
The following is committed to our GIT repositories and will be available in future snapshots and versions (excerpt from change log):

> https://github.com/squirrel-sql-client/squirrel-sql-code/issues/50
>   SQL result and table export to CSV or XML:
>   New formatting option "Include grouping separator if configured in Global Preferences"
>   which is applicable when the option "Use formatting as configured in Global Preferences" is used.
>   See section "Formatting" near the bottom of the export dialog.

**Comment by t603** [comment]
Hello, Gerd, 

I tested squirrel-sql-snapshot-20241208_2056-standard.jar on Eclipse Adoptium OpenJDK Runtime Environment both the latest 17 and 23 and it looks like it works OK exactly as I asked. I will make further tests on another computer with Czech local settings. 

One more interesting thing is, that in this settings or in this version the problem with corrupted XLSX reported only in Libre Office in [Basic formatting of only the first line (header) of XLSX export: Bold, Center, Filter, Freeze Top Row](https://github.com/squirrel-sql-client/squirrel-sql-code/issues/46) does not appear anymore, which is great. 

Thank You very much, Stepan

**Comment by t603** [comment]
Hello, Gerd,

I tested squirrel-sql-snapshot-20241214_2028-standard.jar on Eclipse Adoptium OpenJDK Runtime Environment both the latest 21.0.5+11-LTS on another computer with Czech locale and region settings and it works OK exactly as I asked when I used "Use locale-dependent format" in Global Preferences -> Data Type Controls -> FLOAT... 

Test Case: 
```
--H2 2.3.232 InMemory 
drop table if exists "t"; 
create table "t" ("price" numeric (10,2), "purchaseDate" timestamp); 
insert into "t" ("price", "purchaseDate") values (1234567.89, current_timestamp()); 
select "price", "purchaseDate" from "t"; 
```

The result in SQuirreL SQL was correctly with spaces among thousands and there was no spaces in CSV export: 

```
price,purchaseDate
"1234567,89",2024-12-18 10:01:16.984126
```

So thank You again very much and I am going to close this issue. Regards, Stepan
