### ISSUE TITLE
Expansion state of alias folders is not visible (no folder icons)

### ISSUE THREAD

**Issue by fml2** [squirrel-sql-client/squirrel-sql-code#53]
Hello,

I'm using SQuirreL SQL Client snapshot-20241208_2056.

In the list of aliases, it's possible to create folders to better organize them. Bur for me, the folder icons are not displayed. When I create a new folder, an icon is displyed to the left from it. But once I expand that folder, the icon disapperars. For existing folders, the icons are also not displayed. There is even no space for them.

The folders can be expanded and collapsed by double clicking on them, but not via icons.

I don't know whether it's because of the L&F used (I use the flat L&F in the variante "IntelliJ").

Thank you!

**Comment by gerdwagner** [comment]
The following was implemented and will be available in future snapshots and versions:

> https://github.com/squirrel-sql-client/squirrel-sql-code/issues/53
>   Aliases tree display:
>   Alias folder icons now show if a folder is expanded or collapsed.
>   New Alias icon was introduced.
>
