### ISSUE TITLE
Writing SQL results to file does not work when using <alias>.<table> addressing

### ISSUE THREAD

**Issue by rodj59** [squirrel-sql-client/squirrel-sql-code#6]
I have a cross database SQL query, using the Unity driver, that produces output within the Results pane okay and yet if I try to send the results via Write to File (any file type) it fails.

Whether this is to do with the fact that other database connections don't accept <alias>.<table> syntax (in my instance I am using SQLite), I don't know. but it does recognize the fact that I was trying to specify a database within the query.. because it complains.

**Comment by gerdwagner** [comment]
Fix is committed to our Git repositories and will be available in future snapshots and versions.

Excerpt from change log:
`https://github.com/squirrel-sql-client/squirrel-sql-code/issues/6
  Exporting SQLs to file (open tools popup (ctl+t) and choose "sql2file") did not work
  for the multi source UnityJDBC driver (https://unityjdbc.com) / MultisSource Plugin.`

**Comment by rodj59** [comment]
Thank you. I look forward to trying it.
